evinkls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('video/', include('video.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/', views.category_videos, name='category_videos'),
    path('video/<int:id>/<slug:slug>/', views.video_detail, name='video_detail'),
    path('search/', views.video_search, name='video_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('faq/', views.faq, name='faq'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

video/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=70)
    address = models.CharField(max_length=120)
    phone = models.CharField(max_length=15)
    fax = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    smtpserver = models.CharField(max_length=20)
    smtpemail = models.CharField(max_length=20)
    smtppassword = models.CharField(max_length=20)
    smtpport = models.CharField(max_length=5)
    icon = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=60)
    instagram = models.CharField(blank=True,max_length=60)
    twitter = models.CharField(blank=True,max_length=60)
    aboutus = RichTextUploadingField()
    contact = RichTextUploadingField()
    referans = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Read', 'Okundu'),
        ('Closed', 'Kapalı'),
    )
    name = models.CharField(max_length=25)
    email = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=255)
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=120)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Contact Form Message"
        verbose_name_plural = "Contact Form Message"

class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name' :  TextInput(attrs={'id':'Name & Surname' ,'class':'form-control unicase-form-control text-input'}),
            'subject' :  TextInput(attrs={'id': 'Subject','class':'form-control unicase-form-control text-input'}),
            'email': TextInput(attrs={'id': 'Email Address','class':'form-control unicase-form-control text-input'}),
            'message': Textarea(attrs={'id': 'Your Message','class':'form-control unicase-form-control'}),

        }

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/user/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '[' +self.user.username +'] ' +self.user.first_name + ' ' +self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    siranumara = models.CharField(blank=True, max_length=20)
    question = models.CharField(blank=True, max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS )
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

video/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    image=models.ImageField(blank=True,upload_to='images/')
    status=models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = models.ForeignKey('self', blank=True ,null=True, related_name='children', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

class Video(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    video=models.FileField(upload_to="video/%y",blank=True)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'
    def get_absolute_url(self):
        return reverse('product _detail', kwargs={'slug': self.slug})

class Galeri(models.Model):
    video= models.ForeignKey(Video,on_delete=models.CASCADE)
    title = models.CharField(max_length=75,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(blank=True, max_length=50)
    comment = models.CharField(blank=True, max_length=255)
    rate = models.IntegerField(blank=True,)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True,max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

class Videoglr(models.Model):
    video= models.ForeignKey(Video,on_delete=models.CASCADE)
    title = models.CharField(max_length=75,blank=True)
    videono = models.IntegerField()
    videos = models.FileField(upload_to="video/%y",blank=True)
    def __str__(self):
        return self.title

home/views.py
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.form import SearchForm, SignUpForm
from home.models import Setting, ContactForm, ContactFormMessage, UserProfile, FAQ
from order.models import ShopCart
from video.models import Video, Category, Galeri, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Video.objects.all()[:4]
    category = Category.objects.all()
    hotvideos = Video.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    lastvideos = Video.objects.all().order_by('-id')[:5]
    context = {'setting': setting,
               'sliderdata': sliderdata,
               'category': category,
               'lastvideos': lastvideos,
               'hotvideos': hotvideos,
               'shopcart': shopcart,
               'page': 'home',}
    return render(request, 'index.html',context)

def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    context = {'setting': setting,'shopcart': shopcart, 'page': 'hakkimizda'}
    return render(request, 'hakkimizda.html', context)

def iletisim(request):

    if request.method == 'POST': # form post edildiyse
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactFormMessage() # modelle bağlantı kur
            data.name = form.cleaned_data['name'] # formdan bilgiyi al
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save() #veri tabanına kaydetme
            messages.success(request, "Mesaj gönderme başarılı!")
            return HttpResponseRedirect ('/iletisim')

    setting = Setting.objects.get(pk=1)
    form=ContactForm()
    context = {'setting': setting, 'form': form}
    return render(request, 'iletisim.html',context)

def category_videos(request,id,slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    videos = Video.objects.filter(category_id=id)
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    context = {'videos': videos,'category': category,'categorydata': categorydata,'shopcart': shopcart }
    return render(request, 'videos.html', context)

def video_detail(request,id,slug):
    category = Category.objects.all()
    video = Video.objects.get(pk=id)
    images = Galeri.objects.filter(video_id=id)
    comments = Comment.objects.filter(video_id=id)
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    context = {'video': video,
               'category': category,
               'images': images,
               'comments': comments,
               'shopcart': shopcart,
                }
    return render(request, 'video_detail.html', context)

def video_search(request):
    if request.method == 'POST':  # form post edildiyse
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']
            videos = Video.objects.filter(title__icontains=query)

            context = {'videos': videos,
                       'category': category,
                       }
            return render(request, 'videos_search.html', context)

    return HttpResponseRedirect('/')

def logout_view(request):
    logout(request)
    messages.success(request, "Yine Bekleriz...")
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            messages.success(request, "Giriş Yapıldı :) ")
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Hatalı Giriş ! | K.adı veya Şifre Yanlış!")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    context = {'category': category,
               }
    return render(request, 'login.html', context)

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request,user)
            #Create data in profile table
            current_user = request.user
            data=UserProfile()
            data.user_id=current_user.id
            data.image ="images/user/user.png"
            data.save()
            messages.success(request, "Siteye Başarılı Bir Şekilde Kayıt Oldunuz... ")
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }
    return render(request, 'signup.html', context)

def faq(request):
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('siranumara')
    context = {'category': category,
               'faq': faq,
               }
    return render(request, 'faq.html',context)

video/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
from video.models import CommentForm, Comment


def index(request):
    return HttpResponse("Video Sayfası")

@login_required(login_url='/login')
def addcomment(request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST': # form post edildiyse
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user=request.user

            data = Comment() # modelle bağlantı kur
            data.user_id = current_user.id
            data.video_id =id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save() #veri tabanına kaydetme
            messages.success(request, "Yorum gönderme başarılı!")
            url = request.META.get('HTTP_REFERER')
            return HttpResponseRedirect(url)

    messages.warning(request, "Uyarı! Yorum gönderme başarışız!")
    return HttpResponseRedirect(url)

home/templates/faq.html
{% extends "homebase.html" %}
{% block title %}S.S.S. {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %}  {{ setting.description }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="breadcrumb">
            <div class="container">
                <div class="breadcrumb-inner">
                    <ul class="list-inline list-unstyled">
                        <li><a href="/">Anasayfa</a></li>
                        <li class='active'>S.S.S.</li>
                    </ul>
                </div><!-- /.breadcrumb-inner -->
            </div><!-- /.container -->
        </div><!-- /.breadcrumb -->

        <div class="body-content outer-top-bd">
            <div class="container">
		<div class="checkout-box faq-page inner-bottom-sm">
			<div class="row">
				<div class="col-md-12">
					<h2>Sıkça Sorulan Sorular</h2>
					<span class="title-tag">En Son Güncelleme 2 Mayıs 2022</span>
					<div class="panel-group checkout-steps" id="accordion">
						<!-- checkout-step-01  -->
{% for rs in faq %}
<div class="panel panel-default checkout-step-02">

	<!-- panel-heading -->
		<div class="panel-heading">
    	<h4 class="unicase-checkout-title">
	        <a data-toggle="collapse" class="collapsed" data-parent="#accordion" href="#collapse{{ rs.siranumara }}">
	          <span>{{ rs.siranumara }}</span>{{ rs.question }}
	        </a>
	     </h4>

    </div>
    <!-- panel-heading -->

	<div id="collapse{{ rs.siranumara }}" class="panel-collapse collapse" style="height: 0px;">

		<!-- panel-body  -->
	    <div class="panel-body">
	    	{{ rs.answer }}
		</div>
		<!-- panel-body  -->

	</div><!-- row -->
</div>
<!-- checkout-step-01  -->
{% endfor %}

					</div><!-- /.checkout-steps -->
				</div>
			</div><!-- /.row -->
		</div><!-- /.checkout-box -->
        </div><!-- /.body-content -->
    </div>
</div>
{% endblock %}

home/templates/hakkimizda.html
{% extends "homebase.html" %}
{% block title %}Hakkımızda- {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %}  {{ setting.description }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="breadcrumb">
            <div class="container">
                <div class="breadcrumb-inner">
                    <ul class="list-inline list-unstyled">
                        <li><a href="/">Anasayfa</a></li>
                        <li class='active'>About As</li>
                    </ul>
                </div><!-- /.breadcrumb-inner -->
            </div><!-- /.container -->
        </div><!-- /.breadcrumb -->

        <div class="body-content outer-top-bd">
            <div class="container">
                <div class="track-order-page inner-bottom-sm">
                    <div class="row">
                        <div class="col-md-12">
            <h2>HAKKIMIZDA</h2>
            <span class="title-tag inner-top-vs">
               {{ setting.aboutus|safe }}
            </span>

        </div>			</div><!-- /.row -->
                </div><!-- /.sigin-in-->

        <!-- ============================================== BRANDS CAROUSEL : END ============================================== -->
            </div><!-- /.container -->
        </div><!-- /.body-content -->
    </div>
</div>
{% endblock %}

home/templates/index.html
{% extends "homebase.html" %}
{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %}  {{ setting.description }} {% endblock %}


{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block content %}
    {% include "content.html" %}
{% endblock %}

home/templates/video_detail.html
{% extends "homebase.html" %}
{% block title %}{{ video.title }} {% endblock %}
{% block keywords %} {{ video.keywords }}  {% endblock %}
{% block description %}  {{ video.description }} {% endblock %}

{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="breadcrumb">
            <div class="container">
                <div class="breadcrumb-inner">
                    <ul class="list-inline list-unstyled">
                        <li><a href="/">Anasayfa</a></li>
						<li class='active'><a href="/category/{{ video.category_id }}/{{ video.category.slug }}">{{ video.category}}</a></li>
                    </ul>
                </div><!-- /.breadcrumb-inner -->
            </div><!-- /.container -->
        </div><!-- /.breadcrumb -->
<!-- --------------------------------------------------------------------ANA YER   --------------------------- -->
        <div class="body-content outer-top-bd">
	<div class="container">
		<div class="sign-in-page inner-bottom-sm">
			<div class="row">
				<!-- Sign-in -->
<div class="col-md-6 col-sm-6 sign-in">

	<div id="owl-main" class="owl-carousel owl-inner-nav owl-ui-sm">
							{% for rs in images %}
							<div class="carousel-item">
							<div class="view">
								<img class="d-block w-100" src="{{ rs.image.url }}" alt="First slide" height="400" width="555">
								<div class="mask rgba-black-light"></div>
							</div>

							</div>
							{% endfor %}
							</div><!-- /.owl-carousel -->
</div>
<!-- Sign-in -->

<!-- create a new account -->
<div class="col-md-6 col-sm-6 create-new-account">
	<h2 class="checkout-subtitle">{{ video.title }}</h2>
	<span class="checkout-subtitle outer-top-xs"></span>
	<div class="checkbox">
	  	<label class="checkbox">
		  	<i class="icon fa fa-video-camera"></i> 42 saat uzunluğunda hazır video içeriği
		</label>
		<label class="checkbox">
		  	<i class="icon fa fa-file"></i> 79 makale
		</label>
		<label class="checkbox">
		  	<i class="icon fa fa-download"></i> 68 indirilebilir kaynak
		</label>
		<label class="checkbox">
		  	<i class="icon fa fa-graduation-cap"></i> Bitirme Sertifikası
		</label>
		<label class="checkbox">
		  	<i class="icon fa fa-money"></i> Uygun Fiyat Garantisi </br>
		</label>
		<label class="checkbox">
		  	<a href="/order/addtocart/{{ video.id }}" class="btn btn-primary"><i class="fa fa-shopping-cart inner-right-vs"></i>SEPETE EKLE</a>
		</label>
		<p></p>
		<label class="checkbox">
		  	<p>Detaylar Açıklama Kısmında Mevcuttur.</p>
		</label>
	</div>


</div>
<!-- create a new account -->			</div><!-- /.row -->
		</div><!-- /.sigin-in-->
	</div><!-- /.container -->
</div>
		<div class="col-md-12">

						<div class="product-tabs outer-top-smal  wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;">

						<ul id="product-tabs" class="nav nav-tabs nav-tab-cell-detail">
							<li class="active"><a data-toggle="tab" href="#description">YORUMLAR</a></li>
							<li class=""><a data-toggle="tab" href="#review">YORUM YAP</a></li>
							<li class=""><a data-toggle="tab" href="#tags">AÇIKLAMA</a></li>
							<li class=""><a data-toggle="tab" href="#fragman">FRAGMAN</a></li>
						</ul><!-- /.nav-tabs #product-tabs -->


						<div class="tab-content outer-top-xs">

							<div id="description" class="tab-pane active">
								<div class="product-tab">
									<div class="blog-write-comment m-t-20">
								{% for rs in comments %}
							<div class="blog-comments inner-bottom-xs">
								<h4><i class="fa fa-user"></i>  {{ rs.user.first_name }}</h4>

								<span class="review-action pull-right">
									{{ rs.created_at }}
									Puan:{{ rs.rate }}
								</span></br>
								<p>{{ rs.comment }}</p>
							</div>
							{% endfor %}
							</div>
								</div>
							</div><!-- /.tab-pane -->

							<div id="review" class="tab-pane">
								<div class="blog-write-comment m-t-20">
								<div class="row">
									<div class="col-md-12">
										<h4>YORUM YAPIN</h4>
										{% if messages %}
                                    {% for message in messages %}
                                    <div class="alert alert-{{message.tags}}" role="alert">
                                        {{ message }}
                                    </div>
                                    {% endfor %}
                                    {% endif %}
									</div>
									<div class="col-md-12">
										<form action="/video/addcomment/{{ video.id }}" class="register-form" role="form" method="post">
											{% csrf_token %}
											<div class="form-group">
												<label class="info-title">Konu </label>
											<input type="text" class="form-control unicase-form-control text-input" id="id_sucject" name="subject" placeholder="Buraya Yazınız...">
											<label class="info-title">Mesajınız </label>
												<textarea class="form-control unicase-form-control" id="id_comment" name="comment" placeholder="Buraya Yazınız..."></textarea>
											<label class="info-title">Puanınız(1-5):&nbsp;&nbsp;</label><div class="rating "> <input type="radio" name="rate" value="1" id="5"><label for="5"></label> <input type="radio" name="rate" value="2" id="4"><label for="4"></label> <input type="radio" name="rate" value="3" id="3"><label for="3"></label> <input type="radio" name="rate" value="4" id="2"><label for="2"></label> <input type="radio" name="rate" value="5" id="1"><label for="1"></label> </div>
										  	</div>

											{% if user.id is not None %}
											<button type="submit" class="btn-upper btn btn-primary checkout-page-button">Gönder</button>
											{% else %}
											Yorum Eklemek için giriş yapınız...
											{% endif %}
										</form>
									</div>
								</div>
							</div>
						</div><!-- /.yORUM YAP -->


								<div id="tags" class="tab-pane">
									<div class="product-tag">

										<h4 class="title">Video detail</h4>
										{{ video.detail|safe }}

									</div><!-- /.product-tab -->
								</div><!-- /.tab-pane -->
								<div id="fragman" class="tab-pane">
									<div class="product-tag">

										<div class="form-group" with>
						<h3 class="name">{{ video.title }} Serisi Tanıtım</h3>
						<video
						id="my-video"
						class="video-js"
						controls
						preload="auto"
						width="720"
						height="480"
						poster="{{ video.image.url }}"
						data-setup="{
						'controls': true,
						'autoplay': false,
						'preload': 'auto'
						}">
						<source src="{{ video.video.url }}" type="video/mp4" />
						<source src="{{ video.video.url }}" type="video/webm" />
					  </video>
							</div>

									</div><!-- /.product-tab -->
								</div><!-- /.tab-pane -->


							</div><!-- /.tab-content -->

						</div>
							</div>
		<!-- --------------------------------------------------------------------ANA YER -------------------------------->
    </div>
</div>
{% endblock %}

home/templates/videos_search.html
{% extends "homebase.html" %}
{% block title %} Site Arama Sonuçları {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %}  {{ setting.description }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="breadcrumb">
            <div class="container">
                <div class="breadcrumb-inner">
                    <ul class="list-inline list-unstyled">
                        <li><a href="/">Ansayfa</a></li>
                        <li class='active'>Sonuç</li>
                    </ul>
                </div><!-- /.breadcrumb-inner -->
            </div><!-- /.container -->
        </div><!-- /.breadcrumb -->

        <table class="table table-bordered">
														<thead>
															<tr>
																<th>Resim</th>
																<th>Video İsmi</th>
																<th>Kategorisi</th>
																<th>Fiyatı</th>
															</tr>
														</thead>
														<tbody>
                                                        {% for rs in videos %}
															<tr>
																<td><a href="/video/{{ rs.id }}/{{ rs.slug }}"><img  src="{{ rs.image.url }}" height="100" width="100" alt=""></a></td>
																<td><h3 class="name"><a href="/video/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></h3></td>
																<td><a href="/category/{{ rs.category_id }}/{{ rs.category.slug }}">{{ rs.category}}</a></td>
																<td><h3 class="name">{{ rs.price }} TL</h3></td>
															</tr>
                                                        {% endfor %}
														</tbody>
													</table>

    </div>
</div>
{% endblock %}